### PR TITLE
Append mixin config name to the injected method

### PR DESCRIPTION
**Pull request by shedaniel**
If a crash is related to a mixin, we don't know who is responsible, this pr adds the mixin config name to the injected method to be clear.

### CODE REVIEW

**Comment by shedaniel** [comment]
This PR is not a duplicate of fabric-loader#271. That PR adds the modid to the mixin config path, while this PR adds the mixin config path to the injected method itself when currently you will only see an equivalent of handler$be001$epicInject

**Review by MaryWeeb — APPROVED** [review]

**Comment by modmuss50** [comment]
Seems like a resonable change, thoughts about making this the modid along with #37 ?

**Comment by shedaniel** [comment]
will do after that one is merged

**Comment by modmuss50** [comment]
Superseeded by https://github.com/FabricMC/Mixin/pull/97 Thanks a lot 👍

**Pull request closed without merging**
